version: '2'

services:
  jenkins:
    container_name: myjenkins
    restart: alwayes
    image: lw96/java8-jenkins-maven-git-vim:latest
    ports:
    - "8080:8080"
    volumes:
    - /srv/docker/jenkins_home:/jenkins

